Info/Controllers/HomeController.cs
using Info.Data;
using Info.Models;
using Info.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace Info.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            HomeDataVM homeData = new();
            homeData.DisplayCategories = _context.Categories?
                .Where(c => c.Active == true && c.Display == true);
            homeData.Authors = _context.Texts.Include(a => a.User).Select(a => a.User).Distinct();
            return View(homeData);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Info/Controllers/TextsController.cs
using Info.Data;
using Info.Infrastructure;
using Info.Models;
using Info.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;
using Text = Info.Models.Text;

namespace Info.Controllers
{
    public class TextsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IWebHostEnvironment _hostEnvironment;

        public TextsController(ApplicationDbContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _hostEnvironment = environment;
        }

        // GET: Texts
        public async Task<IActionResult> Index(string Fraza, string Autor, int? Kategoria, int PageNumber = 1)
        {
            var SelectedTexts = _context.Texts?
                 .Include(t => t.Category)
                 .Include(t => t.User)
                 .Where(t => t.Active == true)
                 .OrderByDescending(t => t.AddedDate);

            if (Kategoria != null)
            {
                SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Category.CategoryId == Kategoria);
            }
            if (!String.IsNullOrEmpty(Autor))
            {
                SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.User.Id == Autor);
            }
            if (!String.IsNullOrEmpty(Fraza))
            {
                SelectedTexts = (IOrderedQueryable<Text>)SelectedTexts.Where(r => r.Content.Contains(Fraza));
            }

            TextsViewModel textsViewModel = new();
            textsViewModel.TextsView = new TextsView();

            textsViewModel.TextsView.TextCount = SelectedTexts.Count();
            textsViewModel.TextsView.PageNumber = PageNumber;
            textsViewModel.TextsView.Author = Autor;
            textsViewModel.TextsView.Phrase = Fraza;
            textsViewModel.TextsView.Category = Kategoria;

            textsViewModel.Texts = (IEnumerable<Text>?)await SelectedTexts
                .Skip((PageNumber - 1) * textsViewModel.TextsView.PageSize) 
                .Take(textsViewModel.TextsView.PageSize)
                .ToListAsync();

            ViewData["Category"] = new SelectList(_context.Categories?
                .Where(c => c.Active == true),
                "CategoryId", "Name", Kategoria);

            ViewData["Author"] = new SelectList(_context.Texts
                .Include(u => u.User)
                .Select(u => u.User)
                .Distinct(),
                "Id", "FullName", Autor);

            return View(textsViewModel);
        }

        // GET: Texts
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> List()
        {
            var applicationDbContext = _context.Texts.Include(t => t.Category).Include(t => t.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Texts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Texts == null)
            {
                return NotFound();
            }

            TextWithOpinions textWithOpinions = new TextWithOpinions();

            textWithOpinions.SelectedText = await _context.Texts
                .Include(t => t.Category)
                .Include(t => t.User)
                .Include(t => t.Opinions)
                .ThenInclude(c => c.User)
                .Where(t => t.Active == true)
                .FirstOrDefaultAsync(m => m.TextId == id);
               
            if (textWithOpinions.SelectedText == null)
            {
                return NotFound();
            }
            textWithOpinions.NewOpinion = new Opinion { TextId = (int)id, 
                                    Id=textWithOpinions.SelectedText.Id };

            textWithOpinions.ReadingTime = (int)Math.Ceiling((double)textWithOpinions.SelectedText.Content.Length / 1400);

            textWithOpinions.CommentsNumber = _context.Opinions
                .Where(x => x.TextId == id)
                .Count();

            if (textWithOpinions.CommentsNumber != 0)
            {
                textWithOpinions.OpinionsNumber = _context.Opinions.Where(o => o.TextId == id).Where(x => x.Rating != null).Count();
                if(textWithOpinions.OpinionsNumber != 0)
                {
                    textWithOpinions.AverageScore = (float)(textWithOpinions.OpinionsNumber > 0 ? _context.Opinions.Where(o => o.TextId == id).Where(x => x.Rating != null).Average(x => (int)x.Rating) : 0);
                }
            }

            textWithOpinions.Description = Variaty.Phrase("komentarz", "komentarze", "komentarzy", textWithOpinions.CommentsNumber);
            

            return View(textWithOpinions);
        }

        // GET: Texts/Create
        [Authorize(Roles = "admin, author")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name");
            return View();
        }

        // POST: Texts/Create
        [Authorize(Roles = "admin, author")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TextId,Title,Summary,Keywords,Content,Active,CategoryId")] Info.Models.Text text, IFormFile picture)
        {
            if (ModelState.IsValid)
            {
                //odczytanie identyfikatora użytkownika i bieżącej daty
                text.Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                text.AddedDate = DateTime.Now;

                //zapisanie obrazka i przeskalowanej wersji
                if (picture != null && picture.Length > 0)
                {
                    ImageFileUpload imageFileResult = new(_hostEnvironment);
                    FileSendResult fileSendResult = imageFileResult.SendFile(picture, "img", 600);
                    if (fileSendResult.Success)
                    {
                        text.Graphic = fileSendResult.Name;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Wybrany plik nie jest obrazkiem!";
                        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
                        return View(text);
                    }
                }

                _context.Add(text);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
            return View(text);
        }

        // GET: Texts/Edit/5
        [Authorize(Roles = "admin, author")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Texts == null)
            {
                return NotFound();
            }

            var text = await _context.Texts.FindAsync(id);
            if (text == null)
            {
                return NotFound();
            }

            if(string.Compare(User.FindFirstValue(ClaimTypes.NameIdentifier), text.Id) == 0 || User.IsInRole("admin"))
            {
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
                ViewData["Author"] = text.Id;
                return View(text);
            }
            else
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Texts/Edit/5
        [Authorize(Roles = "admin, author")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int textid, [Bind("TextId,Title,Summary,Keywords,Content,Graphic,Active,AddedDate,CategoryId,Id")] Info.Models.Text text, IFormFile? picture)
        {
            if (textid != text.TextId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {

                //zapisanie obrazka i przeskalowanej kopii
                if (picture != null && picture.Length > 0)
                {
                    ImageFileUpload imageFileResult = new(_hostEnvironment);
                    FileSendResult fileSendResult = imageFileResult.SendFile(picture, "img", 600);
                    if (fileSendResult.Success)
                    {
                        text.Graphic = fileSendResult.Name;
                    }
                    else
                    {
                        ViewBag.ErrorMessage = "Wybrany plik nie jest obrazkiem!";
                        ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
                        ViewData["Author"] = text.Id;
                        return View(text);
                    }
                }

                try
                {
                    _context.Update(text);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TextExists(text.TextId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Name", text.CategoryId);
            ViewData["Author"] = text.Id;
            return View(text);
        }

        // GET: Texts/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Texts == null)
            {
                return NotFound();

Info/Views/Home/Index.cshtml
@model Info.Models.ViewModels.HomeDataVM;
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
    ViewData["Title"] = "Witamy";
}

<div class="container">

    <!-- Kategorie -->
    <div class="row text-center py-5">
        @foreach (var item in Model.DisplayCategories)
        {
            <div class="col-md-6 col-lg-4 my-3">
                <a class="text-primary" asp-action="Index" asp-controller="Texts" asp-route-Kategoria="@item.CategoryId">
                    <i class="bi-@item.Icon" style="font-size: 4rem;"></i>
                </a>
                <h2 class="oswald">@item.Name</h2>
                <p>@item.Description </p>          
            </div>
        }
    </div>

    <!-- Autorzy -->
    <div class="row py-5">
        <div id="carousel-autorzy" class="carousel carousel-dark slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
                <button type="button" data-bs-target="#carousel-autorzy" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                @for (int i=1; i <= Model.Authors.Count(); i++)
                {
                    <button type="button" data-bs-target="#carousel-autorzy" data-bs-slide-to="@i" aria-label="Slajd @i"> </button>
                }
            </div>

            <div class="carousel-inner">
                <div class="carousel-item active">
                    <!-- zmiany w celu uzyskania responsywności -->
                    <div class="row ">
                        <div class="col-lg-4 ">
                            <img src="~/photo/mini/autorzy.jpg" alt="autorzy tekstów" class="rounded-circle mx-auto d-block" width="250">
                        </div>
                        <div class="col-lg-8">
                            <h2 class="fw-bolder text-success oswald">Twórcy portalu</h2>
                            <p class="fs-5 py-3">Z portalem współpracują uznani programiści oraz studenci, którzy chcą rozwijać swoje umiejętności i zdobywać doświadczenie praktyczne. Dołącz do naszego zespołu! Zarejestruj się już dziś.</p>
                        </div>
                    </div>
                </div>
                @foreach (var item in Model.Authors)
                {
                    <div class="carousel-item">
                        <div class="row">
                            <div class="col-lg-4">
                                <img src="@Url.Content(item.Photo == null ? "~/photo/mini/user.png" : "~/photo/mini/" + item.Photo)" alt="@item.FullName" class="rounded-circle mx-auto d-block" width="250">
                            </div>
                            <div class="col-lg-8">
                                <h2 class="fw-bolder text-success oswald">@item.FirstName</h2>
                                <p class="fs-5 py-3">@item.Information</p>
                            </div>
                        </div>
                    </div>
                }
            </div>  <!-- carousel-inner -->
        </div> <!-- carousel-->
    </div>  <!-- row-->
</div> <!-- kontener-->

<!-- Dane adresowe -->
<div class="row py-5 bg-back">
    <section class="col-md-4">
        <div class="row ms-3">
            <div class="ps-5 my-3 col-6 col-md-12">
                <img src="~/graphic/ikona.png" width="120" alt="InfoInfo" class="rounded-circle" />
            </div>
            <div class="my-3 pt-3 col-6 col-md-12">
                <p class="text-light"><i class="bi-geo-fill"></i> Płock, al. Kilińskiego 12</p>
                <p class="text-light"><i class="bi-telephone-fill"></i> +48 24 366 41 00</p>
                <p class="text-light"><i class="bi-envelope-fill"></i> infoinfo@wlodkowic.pl</p>
            </div>
        </div>
    </section>

    <section class="col-md-8">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4852.826189614571!2d19.70572296760938!3d52.54405224686102!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471c7090b9c877d9%3A0x2d43661b0a4753e!2sSzko%C5%82a+Wy%C5%BCsza+im.+P.+W%C5%82odkowica!5e0!3m2!1spl!2spl!4v1507835432473" frameborder="0" style="border:0; width: 100%; height: 350px;" allowfullscreen></iframe>
    </section>
</div>