Info/Models/Opinion.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Info.Models
{
    public class Opinion
    {
        [Key]
        [Display(Name = "Identyfikator:")]
        public int OpinionId { get; set; }

        [Required(ErrorMessage = "Proszę podać treść komentarza.")]
        [Display(Name = "Treść komentarza:")]
        [DataType(DataType.MultilineText)]
        public string? Comment { get; set; }

        [Display(Name = "Data dodania:")]
        [DataType(DataType.Date, ErrorMessage = "Niepoprawny format daty")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy HH:mm}")]
        public System.DateTime AddedDate { get; set; }

        [Display(Name = "Ocena tekstu:")]
        public TypeOfGrade? Rating { get; set; }

        [Required]
        [Display(Name = "Komentowany tekst:")]
        public int TextId { get; set; }
        //Komentowany tekst
        [ForeignKey("TextId")]
        public virtual Text? Text { get; set; }

        [Display(Name = "Autor komentarza:")]
        public string? Id { get; set; }
        //Autor komentarza
        [ForeignKey("Id")]
        public virtual AppUser? User { get; set; }
    }
   
    public enum TypeOfGrade
    {
        super = 5,
        dobry = 4,
        przeciętny = 3,
        słaby = 2,
        nieprzydatny = 1,
    }
}

Info/Controllers/OpinionsController.cs
using Info.Data;
using Info.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data;
using System.Security.Claims;
using Text = Info.Models.Text;

namespace Info.Controllers
{
    public class OpinionsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OpinionsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Opinions
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                var applicationDbContext = _context.Opinions.Include(o => o.Text).Include(o => o.User);
                return View(await applicationDbContext.ToListAsync());
            } 
            else 
            { 
                var appDbContext = _context.Opinions.Include(o => o.Text).Include(o => o.User).Where(o => o.TextId == id);
                return View(await appDbContext.ToListAsync());
            }
        }

        // GET: Opinions/Details/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Opinions == null)
            {
                return NotFound();
            }

            var opinion = await _context.Opinions
                .Include(o => o.Text)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OpinionId == id);
            if (opinion == null)
            {
                return NotFound();
            }

            return View(opinion);
        }

        // GET: Opinions/Create
        [Authorize]
        public IActionResult Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Text text = _context.Texts.Find(id);
            if (text == null)
            { 
                return BadRequest(); 
            }    
            ViewData["IdText"] = id;
            ViewData["TextTitle"] = text.Title;
            return View();
        }

        // POST: Opinions/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OpinionId,Comment,Rating,TextId")] Opinion opinion)
        {
            if (ModelState.IsValid)
            {
                opinion.AddedDate = DateTime.Now;
                opinion.Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _context.Add(opinion);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Texts", new {id=opinion.TextId}, "comments");
            }
            ViewData["IdText"] = opinion.TextId;
            ViewData["TextTitle"] = opinion.Text.Title;

            return View(opinion);
        }

        // POST: Opinions/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePartial([Bind("OpinionId,Comment,Rating,TextId")] Opinion opinion)
        {
            if (ModelState.IsValid)
            {
                opinion.AddedDate = DateTime.Now;
                opinion.Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                _context.Add(opinion);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Texts", new { id = opinion.TextId }, "comments");
            }
            ViewData["IdText"] = opinion.TextId;
            ViewData["TextTitle"] = opinion.Text.Title;

            return RedirectToAction("Details", "Texts", new { id = opinion.TextId }, "comments");
        }

        // GET: Opinions/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Opinions == null)
            {
                return NotFound();
            }

            var opinion = await _context.Opinions.FindAsync(id);
            if (opinion == null)
            {
                return NotFound();
            }
            ViewData["TextId"] = opinion.TextId;
            ViewData["Author"] = opinion.Id;
            return View(opinion);
        }

        // POST: Opinions/Edit/5
        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int OpinionId, [Bind("OpinionId,Comment,Rating")] Opinion opinion)
        {
            if (OpinionId != opinion.OpinionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(opinion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OpinionExists(opinion.OpinionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TextId"] = opinion.TextId;
            ViewData["Author"] = opinion.Id;
            return View(opinion);
        }

        // GET: Opinions/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Opinions == null)
            {
                return NotFound();
            }

            var opinion = await _context.Opinions
                .Include(o => o.Text)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OpinionId == id);
            if (opinion == null)
            {
                return NotFound();
            }

            return View(opinion);
        }

        // POST: Opinions/Delete/5
        [Authorize(Roles = "admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Opinions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Opinions'  is null.");
            }
            var opinion = await _context.Opinions.FindAsync(id);
            if (opinion != null)
            {
                _context.Opinions.Remove(opinion);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OpinionExists(int id)
        {
          return _context.Opinions.Any(e => e.OpinionId == id);
        }
    }
}

Info/Views/Opinions/Create.cshtml
@model Info.Models.Opinion

@{
    ViewData["Title"] = "Dodawanie komentarza";
}

<h1 class="oswald text-primary">Dodawanie komentrza do tekstu</h1>

<h4 class="text-success">@ViewData["TextTitle"]</h4>
<hr />
<div class="row">
    <div class="col-md-6 interspace">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" id="TextId" name="TextId" value="@ViewData["IdText"]" />
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <select asp-for="Rating" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(TypeOfGrade)))"> 
                    <option value="">--- Wybierz ocenę ---</option>
                </select>
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Zapisz ocenę" class="btn btn-primary" />
                <a asp-controller="Texts" asp-action="Details" asp-route-id=@ViewData["IdText"] class="btn btn-light">Powrót do tekstu</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Info/Views/Opinions/CreatePartial.cshtml
@using System.Security.Claims;
@model Info.Models.Opinion
<div class="row interspace">
    <form asp-action="CreatePartial" asp-controller="Opinions" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" id="TextId" name="TextId" value="@Model.TextId"/>
        <div class="form-group">
            <label asp-for="Comment" class="control-label"></label>
            <textarea asp-for="Comment" class="form-control"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>
        @if (User.FindFirstValue(ClaimTypes.NameIdentifier) != Model.Id)
        {
        <div class="form-group">
            <label asp-for="Rating" class="control-label"></label>
            <select asp-for="Rating" class="form-control" asp-items="@new SelectList(Enum.GetNames(typeof(TypeOfGrade)))"> 
                <option value="">--- Wybierz ocenę ---</option>
            </select>
            <span asp-validation-for="Rating" class="text-danger"></span>
        </div>
        }
        <div class="modal-footer">
            <div class="form-group">
                <input type="submit" value="Dodaj opinię" class="btn btn-primary" />
                <button type="button" data-bs-dismiss="modal" class="btn btn-light">Powrót do tekstu</button>
            </div>
        </div>
    </form>
</div>

Info/Views/Opinions/Delete.cshtml
@model Info.Models.Opinion

@{
    ViewData["Title"] = "Usuwanie opinii";
}

<h1 class="oswald text-primary">Kasowanie opinii</h1>

<h3 class="text-success">Czy na pewno chcesz usunąć tę opinię?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FullName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OpinionId" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-light">Powrót do listy</a>
    </form>
</div>

Info/Views/Opinions/Details.cshtml
@model Info.Models.Opinion

@{
    ViewData["Title"] = "Opinia";
}

<h1 class="oswald text-primary">Szczegóły opinii</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comment)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comment)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text.Title)
        </dd>
        <dt class = "col-sm-2">
            Autor:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.FullName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.OpinionId" class="btn btn-warning">Edycja</a>
    <a asp-action="Index" class="btn btn-light">Powrót do opinii</a>
</div>

Info/Views/Opinions/Edit.cshtml
@model Info.Models.Opinion

@{
    ViewData["Title"] = "Edycja opinii";
}

<h1 class="oswald text-primary">Edycja opinii</h1>
<hr />
<div class="row">
    <div class="col-md-8 interspace">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OpinionId" />
            <input type="hidden" asp-for="Id" value=@ViewData["Author"] />
            <input type="hidden" asp-for="AddedDate" />
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <textarea asp-for="Comment" class="form-control"></textarea>
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
                <a asp-action="Details" asp-route-id="@Model.OpinionId" class="btn btn-light">Powrót do opinii</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Info/Views/Opinions/Index.cshtml
@model IEnumerable<Info.Models.Opinion>

@{
    ViewData["Title"] = "Opinie o tekstach";
}

<h1 class="oswald text-primary">Opinie użytkowników</h1>

<table class="table" id="opinie">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Text.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comment)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AddedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.User.FullName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.User.FullName)
            </td>
            <td>
                    <a class="btn btn-outline-primary rounded-circle my-1" title="Szczegóły" asp-action="Details" asp-route-id="@item.OpinionId"><i class="bi-eye" aria-label="Treść opinii"></i></a>
                    <a class="btn btn-outline-warning rounded-circle my-1" title="Edycja" asp-action="Edit" asp-route-id="@item.OpinionId"><i class="bi-pen-fill" aria-label="Edycja opinii"></i></a>
                    <a class="btn btn-outline-danger rounded-circle my-1" title="Usuwanie" asp-action="Delete" asp-route-id="@item.OpinionId"><i class="bi-trash" aria-label="Usuwanie opinii"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts{
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs5/dt-1.13.1/datatables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#opinie').DataTable({
                language: {
                    "decimal": "",
                    "emptyTable": "Brak danych do wyświetlenia",
                    "info": "Pozycje od _START_ do _END_ z _TOTAL_ rekordów",
                    "infoEmpty": "Pozycji 0 z 0 dostępnych",
                    "infoFiltered": "(filtrowanie z _MAX_ dostępnych pozycji)",
                    "infoPostFix": "",
                    "thousands": " ",
                    "lengthMenu": "Pokaż _MENU_ pozycji",
                    "loadingRecords": "Ładowanie...",
                    "processing": "Przetwarzanie...",
                    "search": "Wyszukaj:",
                    "zeroRecords": "Nie znaleziono danych",
                    "paginate": {
                        "first": "Pierwsza",
                        "last": "Ostatnia",
                        "next": "Następna",
                        "previous": "Poprzednia"
                    },
                    "aria": {
                        "sortAscending": ": sortuje kolumnę rosnąco",
                        "sortDescending": ": sortuje kolumnę malejąco"
                    }
                }
            });
        });
    </script>
}